### ISSUE TITLE
Need instructions for slack chatroom login

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/data-team-ru-stat#2]
Joining Slack is a bit tedious (I was not sure which option should I choose upon registration), but it s a great tool for teamwork, hopefully. I think we need:
- some minimal instructions on how to join slack for new users (@Rotzke?)
- should I put invite URL for <https://openstat-team.slack.com> in README.md?

**Comment by Rotzke** [comment]
All they need is to use this link: https://join.slack.com/openstat-team/shared_invite/MTk4MTUzODM3NTM4LTE0OTc1MTczODctMThhNTE3Yzc1NA

I think it's fine to post it in README.
