### ISSUE TITLE
Possible team roles and subtopics

### ISSUE THREAD

**Issue by Rotzke** [epogrebnyak/data-team-ru-stat#4]
Ideas to separate team into specialty groups later on: ETL, Analysis, Visualisation, etc. or engineers, analysts and scientists teams.

- Use personal skills set and user request?
- Separate Slack channel for sub-teams within our Slack team?

_Cookiecutter_ convention's really arranged similar way.

**Comment by epogrebnyak** [comment]
I see there different backgrounds / skill levels / initerests, but let try first get the team running "en masse" and separate a bit later, based on specific issues/tasks. 

in [data-driven cookie-cutter](see readme) I think there following basic stages:
- ```ETL``` - raw data to processed folder 
- ```EDF``` - exploratory data analysis, descriptive statistics, visualisation of canonical dataset
- ```models``` - econometrics or other way of modelling/forecasting (some people will do machine learnign here)
- ```reports``` - more polished results in PDF/notebooks

A separate story is about what can go wrong at each stage that makes a project not reproducible and less efficient.

**Comment by epogrebnyak** [comment]
As a style comment why not use "Possible team separation method" as less striking capitalisation? ;) 
Maybe "Possible team roles"? - it is indeed better unite before seprating.

**Comment by Rotzke** [comment]
Sorry, professional problem - I am a lead editor of a US-based magazine, capitalization habits leaked here.

**Comment by epogrebnyak** [comment]
@Rotzke - does #9 supercede this issue? please close this one if it does.
