### ISSUE TITLE
Live session to discuss project requirements and design Sun, June 18 21:30 (GMT+5:30) 19:00 (GMT+3) 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/data-team-ru-stat#6]
Agenda:
- project requirements 
- design and technical solutions considerations

Venue:
<https://hangouts.google.com/hangouts/_/r7fusbkh3neivjcbabvqgxigsme>

Discussion materials:
- to be published here before the session 

Suggested reading:
- <https://github.com/epogrebnyak/data-team-ru-stat/issues/5> - started parts of discussion 

Time zones: 21:30 (GMT+5:30) - India,  19:00 (GMT+3) - Moscow, Dnipro

Please drop a note below if you are able to join.

**Comment by Rotzke** [comment]
I am in :)

**Comment by Akrishna91** [comment]
I am able to join yeah!

**Comment by Rotzke** [comment]
Also, guys, please join our Slack team (not many people there for some reason): https://join.slack.com/openstat-team/shared_invite/MTk4MTUzODM3NTM4LTE0OTc1MTczODctMThhNTE3Yzc1NA

**Comment by neotheicebird** [comment]
Am in too :)

**Comment by MrBorusLee** [comment]
I'm in

**Comment by rohlin17** [comment]
I'm in

**Comment by epogrebnyak** [comment]
Dear all, here is some material for requiremets, to be continued. Please put in some sort of like / dislike once you read it, but let's discuss it at session. More parts to follow. Please write in Slack for immediate corrections/questions. 

Mission
=======

Enable access to continiously updated macroeconomic, corporate and bank data for Russia.

1. Macroeconomic time series 
============================

User cases 
----------
*User 1 ('Sasha')* is a data analyst. He is proficient is R/pandas and likes CSV files 
better than Excel. He knows to demostrate his work in Jupiter notebooks and 
wants his graphs and models to be continiously updated without him going to download data
manualy. He worked with Quandl and FRED and at work he has paid access to CEIC and Blooomberg.

*User 2 ('Vera')* is also a researcher. She is confident with Excel, so that she can 
do all of her work without depending on programming. Her boss is Excel user too, so there 
is little  point in going to R/pandas. She would consider downloading the data in Excel file,
eg. exhcange rates or interest rates, but only once she trusts the data source. She tried some Excel 
add-ons, but did not like them much. 

*User 3' ('Simon')* is a journalist. He covers Russia economics and once in a while makes comments
about data releases. He calls analysts in banks and research centers to find out thier views 
about newest inflation or household income figure and can deliever plain-word on economic story. He 
is BA in Medieval Literature, so he is not into Excel at all. Simon would rather click on some graphs 
allowing him to interrogate analysts better. He is also keen to post his story on FB or Tweeter before 
other journalists do.

User 4 is a Robot. It learned we have some great open data and wants to borrow from us. 

*Data access methods* by users:
- work with API, download latest data to local file (Sasha and Robot)
- download CSV file from stable URL, save to local file (Sasha)
- download Excel file (Vera)
- repost a graph on Facebook (Simon)


To de continuted

**Comment by Rotzke** [comment]
Well, Vera can use the same .CSV as Sasha in Excel :) Would suggest:
- **API** for _Robot_ and _Sasha_;
- **CSV** for __Sasha__ and __Vera;
- Google Charts on website with sharing option for __Simon__;

**Comment by epogrebnyak** [comment]
You have to know Vera ) she wants three frequencies of variables on
different sheets followed by sheet with varnames. Cannot deny what a woman
wants.

But to sort things out the priority is Sasha and Robot, and Vera and Simon
as add-on features.

18 июн. 2017 г. 11:44 пользователь "Nikita Rotsky" <notifications@github.com>
написал:

**Comment by Rotzke** [comment]
@epogrebnyak Oh, OK, if it is mandatory we could use something like "xlsxwriter" library to convert CSVin to XLS to please this woman ;)

Agree with priorities.

**Comment by rohlin17** [comment]
I spent six years in the Financial and Economic Department of one of the Top 50 Russian banks. Excel is absolutely reporting standard. 
Yes, we developed a big data warehouse and quite complex Business Intelligence system, but Vera will use use Excel forever - she downloads Excel reports from BI system and slice and dice them like she wants on her desktop computer. And here Excel is the best.

**Comment by epogrebnyak** [comment]
Todo after the live session:
- write out a sample graph/pipline of 2-3 parsers to database to API (EP+Marcel)
- think of datachecks: automated validation + 'human eye' (EP+Marcel)
- required AWS instances (Nikita+Boris+Dmitry)

Is this correct?

**Comment by Rotzke** [comment]
Actually, write 1 pipeline with requirements :)

Everything else is correct.
