### ISSUE TITLE
A small poll before the today's meeting on participants work systems

### ISSUE THREAD

**Issue by Rotzke** [epogrebnyak/data-team-ru-stat#7]
<h2>What OS do you have on the machine that will be used for project development?</h2>

- \***NIX**: Please note OS/Distro and possibly it's version and kernel;
- **Windows**: Please note version; <s>and why one would endure such pain?!</s>

**Comment by Rotzke** [comment]
GNU/Linux Debian 9 «Stretch» with custom kernel 4.10

**Comment by neotheicebird** [comment]
Ubuntu 14.04 LTS, windows 7

**Comment by epogrebnyak** [comment]
Windows, because it is office

18 июн. 2017 г. 10:59 пользователь "Prashanth G" <notifications@github.com>
написал:

**Comment by Rotzke** [comment]
@epogrebnyak I thought you will be working from home. What critical restrictions do you have except Slack on that machine, Evgeny?

**Comment by MrBorusLee** [comment]
Ubuntu 14.04 LTS, 16.04 LTS

**Comment by GajanandN** [comment]
Windows10 - I have no problem with it as I use anaconda and Jupyter notebooks for most of my work. Nowadays now using pyCharm with Django. I have dual booted Ubuntu 16.04 too.

**Comment by rohlin17** [comment]
Windows 8, Ubuntu 16.04 as VM

**Comment by Akrishna91** [comment]
Windows 8, Anaconda and virtual env

**Comment by epogrebnyak** [comment]
Maybe we can move this information to #1? What do you think?

**Comment by Rotzke** [comment]
@epogrebnyak Actually, now I know that Data Engineers team use Linux, that's fine, will close the issue.
